"""init schema

Revision ID: e7912d53124b
Revises: 
Create Date: 2026-07-31 09:52:52.989006

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7912d53124b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('reference_image', 'generated_image', 'generated_video', 'thumbnail', 'export', name='asset_type'), nullable=False),
    sa.Column('source', sa.Enum('user_upload', 'generation', 'system', name='asset_source'), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True, comment='视频时长(秒)'),
    sa.Column('access_policy', sa.String(length=32), nullable=False),
    sa.Column('safety_status', sa.Enum('pending', 'pass', 'flagged', 'blocked', 'reviewing', name='safety_status'), nullable=False),
    sa.Column('generation_task_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['generation_task_id'], ['generation_tasks.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_character_id'), 'assets', ['character_id'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_table('characters',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('companion_preference', sa.Text(), nullable=True),
    sa.Column('relationship_template_code', sa.String(length=64), nullable=True),
    sa.Column('personality_template_code', sa.String(length=64), nullable=True),
    sa.Column('persona_prompt', sa.Text(), nullable=True),
    sa.Column('relationship_setting', sa.Text(), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('visual_style_code', sa.String(length=64), nullable=True),
    sa.Column('reference_asset_id', sa.UUID(), nullable=True),
    sa.Column('interaction_bounds', sa.Text(), nullable=True),
    sa.Column('model_params', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'archived', 'deleted', name='character_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reference_asset_id'], ['assets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('quick_topics', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_character_id'), 'conversations', ['character_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('grant', 'purchase', 'subscription', 'freeze', 'consume', 'refund', 'adjust', name='credit_entry_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('related_task_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['related_task_id'], ['generation_tasks.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('image', 'video', name='task_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'success', 'failed', 'cancelled', 'safety_blocked', name='task_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', sa.Text(), nullable=False),
    sa.Column('assembled_prompt', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_task_id', sa.String(length=255), nullable=True),
    sa.Column('provider_model', sa.String(length=64), nullable=True),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('freeze_ledger_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('result_asset_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('safety_status', sa.Enum('pending', 'pass', 'flagged', 'blocked', 'reviewing', name='safety_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['freeze_ledger_id'], ['credit_ledger.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['result_asset_id'], ['assets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_generation_tasks_character_id'), 'generation_tasks', ['character_id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_user_id'), 'generation_tasks', ['user_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_table('templates',
    sa.Column('type', sa.Enum('relationship', 'personality', 'scene', 'style', name='template_type'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_config', sa.Text(), nullable=False, comment='JSON: 名称/描述/图标/预览图'),
    sa.Column('prompt_snippet', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.String(length=512), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_code'), 'templates', ['code'], unique=True)
    op.create_index(op.f('ix_templates_type'), 'templates', ['type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('age_status', sa.Enum('unconfirmed', 'confirmed', 'minor', name='age_status'), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'operator', name='user_role'), nullable=False),
    sa.Column('notification_prefs', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=32), nullable=True),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('email', 'google', 'facebook', name='auth_provider'), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_auth_provider_account'),
    comment='外部身份绑定；一个用户可绑定多个 provider'
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('template_version', sa.String(length=32), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=True),
    sa.Column('feedback', sa.Enum('none', 'like', 'dislike', 'adjust_tone', name='message_feedback'), nullable=False),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('safety_status', sa.Enum('pending', 'pass', 'flagged', 'blocked', 'reviewing', name='safety_status'), nullable=False),
    sa.Column('generation_task_id', sa.UUID(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['generation_task_id'], ['generation_tasks.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('subscription', 'credits', name='order_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', 'cancelled', name='order_status'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('stripe', 'wechat', 'alipay', name='payment_channel'), nullable=False),
    sa.Column('provider_checkout_id', sa.String(length=255), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'cancelled', 'expired', name='subscription_status'), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('entitlements', sa.Text(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.Enum('stripe', 'wechat', 'alipay', name='payment_channel'), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider_price_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', name='uq_subscription_user_channel')
    )
    op.create_index(op.f('ix_subscriptions_provider_subscription_id'), 'subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('works',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('generation_task_id', sa.UUID(), nullable=True),
    sa.Column('primary_asset_id', sa.UUID(), nullable=True),
    sa.Column('scene_template_code', sa.String(length=64), nullable=True),
    sa.Column('style_template_code', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('display_at', sa.String(length=64), nullable=True, comment='展示时间标签'),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['generation_task_id'], ['generation_tasks.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['primary_asset_id'], ['assets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_character_id'), 'works', ['character_id'], unique=False)
    op.create_index(op.f('ix_works_user_id'), 'works', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('preference', 'event', 'relationship', 'important_date', 'fact', name='memory_type'), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'confirmed', 'rejected', 'archived', name='memory_status'), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='用户确认时间'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_character_id'), 'memories', ['character_id'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('generation_task_id', sa.UUID(), nullable=True),
    sa.Column('risk_type', sa.Enum('spam', 'harassment', 'hate', 'sexual', 'violence', 'self_harm', 'crisis', 'minor_safety', 'copyright', 'other', name='risk_type'), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('disposition', sa.Enum('pending', 'reviewing', 'resolved', 'actioned', 'escalated', name='disposition_status'), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('handled_by', sa.UUID(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['generation_task_id'], ['generation_tasks.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_user_id'), 'safety_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_events_user_id'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_character_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_works_user_id'), table_name='works')
    op.drop_index(op.f('ix_works_character_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_type'), table_name='templates')
    op.drop_index(op.f('ix_templates_code'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_generation_tasks_user_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_character_id'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_character_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_character_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
